### ISSUE TITLE
MarkLogic deployment error '/config/query not found for write'

### ISSUE THREAD

**Issue by BhanuAkaveeti** [marklogic/marklogic-data-hub#1338]
Version : 9.0.4

Deploying through gradle, using 'gradle mlDeploy' command. I am trying to deploy data hub framework with 8010 (data-hub-STAGING) and 8011 (data-hub-FINAL) being secured SSL ports.

Error message (debug log is attached with this ticket)

> Task :mlDeployApp
11:49:21.593 [DEBUG] [com.marklogic.client.ext.batch.RestBatchWriter] Thread pool finished shutdown
11:49:21.593 [INFO] [com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader] Loading default query options from file default.xml
11:49:21.600 [INFO] [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor] Shutting down ExecutorService
11:49:22.776 [DEBUG] [com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader] Finished loading modules from base directory: classpath*:/ml-modules
11:49:22.778 [DEBUG] [com.marklogic.client.impl.OkHttpServices] Connecting to imml-db07d at 8012 as admin
11:49:22.784 [DEBUG] [com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader] Loading modules from base directory: classpath*:/ml-modules-traces
11:49:22.785 [DEBUG] [com.marklogic.com.marklogic.client.ext.modulesloader.impl.SearchOptionsFinder] Finding modules in baseDir: classpath*:/ml-modules-traces
11:49:22.785 [DEBUG] [com.marklogic.com.marklogic.client.ext.modulesloader.impl.SearchOptionsFinder] Finding options modules at path: classpath*:/ml-modules-traces/options/*.*
11:49:22.786 [DEBUG] [org.springframework.core.io.support.PathMatchingResourcePatternResolver] Resolved classpath location [/ml-modules-traces/options/] to resources [URL [jar:file:/C:/Users/akaveb1/.gradle/caches/modules-2/files-2.1/com.marklogic/marklogic-data-hub/3
.0.0/8fb15aae2692f204c5edd9677f57b8df78d884e/marklogic-data-hub-3.0.0.jar!/ml-modules-traces/options/]]
11:49:22.787 [DEBUG] [org.springframework.core.io.support.PathMatchingResourcePatternResolver] Looking for matching resources in jar file [file:/C:/Users/akaveb1/.gradle/caches/modules-2/files-2.1/com.marklogic/marklogic-data-hub/3.0.0/8fb15aae2692f204c5edd9677f57b8df
78d884e/marklogic-data-hub-3.0.0.jar]
11:49:22.787 [DEBUG] [org.springframework.core.io.support.PathMatchingResourcePatternResolver] Resolved location pattern [classpath*:/ml-modules-traces/options/*.*] to resources [URL [jar:file:/C:/Users/akaveb1/.gradle/caches/modules-2/files-2.1/com.marklogic/marklogi
c-data-hub/3.0.0/8fb15aae2692f204c5edd9677f57b8df78d884e/marklogic-data-hub-3.0.0.jar!/ml-modules-traces/options/traces.xml]]
11:49:22.787 [INFO] [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor] Initializing ExecutorService
11:49:22.787 [INFO] [com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader] Loading traces query options from file traces.xml
11:49:22.788 [INFO] [org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor] Shutting down ExecutorService
11:49:22.790 [null] [com.marklogic.client.impl.OkHttpServices]
11:49:22.790 [DEBUG] [com.marklogic.client.impl.OkHttpServices] Putting /config/query/traces
11:49:23.776 [ERROR] [com.marklogic.client.ext.modulesloader.impl.SimpleLoadModulesFailureListener] Error caught while loading modules, cause: Local message: /config/query not found for write. Server Message: Request failed. Error body not received from server
com.marklogic.client.ResourceNotFoundException: Local message: /config/query not found for write. Server Message: Request failed. Error body not received from server
        at com.marklogic.client.impl.OkHttpServices.putPostValueImpl(OkHttpServices.java:2860)
        at com.marklogic.client.impl.OkHttpServices.putValue(OkHttpServices.java:2729)
        at com.marklogic.client.impl.QueryOptionsManagerImpl.writeOptions(QueryOptionsManagerImpl.java:158)
        at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader.lambda$installQueryOptions$3(DefaultModulesLoader.java:508)
        at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader.lambda$executeTask$5(DefaultModulesLoader.java:545)
11:49:22.848 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor]
> Task :mlDeployApp FAILED
[debug.txt](https://github.com/marklogic/marklogic-data-hub/files/2375959/debug.txt)

**Comment by aebadirad** [comment]
DHF version 3.0.0 requires ML 9.05 or later to run

**Comment by grechaw** [comment]
I think this might be an issue with 3.0.0 and deploying search options in general.  This issue is indeed fixed in 4.0.0.  I'm going to close it out as we're trying to get a better view of the overall buglist right now.

**Comment by BhanuAkaveeti** [comment]
Hello,

I used version 2.0.3 but still facing same issue. Please find below the
build.gradle content.

/*
 * This Gradle file shows one approach for supporting a "disconnected"
build - i.e. one that doesn't use any
 * repositories, but rather finds dependencies in a directory structure.
You can run "gradle buildMlDeployer", and then
 * unzip that file anywhere and run all the ml-gradle tasks as you normally
would.
 *
 * The presence of a property named "disconnected" is what tells the build
file to run in disconnected mode. It is
 * automatically set to true in the gradle.properties file that's included
in the zip produced by "buildMlDeployer".
 *
 * There are other ways to solve the problem of running Gradle when it's
not possible to connect to artifact
 * repositories - this is just one approach.
 *
 * I think the old "apply" approach for plugins is needed here, I don't
think the plugins DSL will work
 * against a file tree.
 */
buildscript {
    if (project.hasProperty("disconnected")) {
        dependencies {
            classpath fileTree(dir: "ml-data-hub-dependencies", include:
"*.jar")
        }
    }
    else {
        repositories {
            jcenter()
        }
        dependencies { classpath "com.marklogic:marklogic-data-hub:2.0.3" }
    }
}

plugins {
    id 'java'
    id 'eclipse'
    id 'idea'

    // This plugin allows you to create different environments
    // for your gradle deploy. Each environment is represented
    // by a gradle-${env}.properties file
    // See https://github.com/stevesaliman/gradle-properties-plugin
    // specify the env on the command line with:
    // gradle -PenvironmentName=x ...
    id 'net.saliman.properties' version '1.4.6'

    // This gradle plugin extends the ml-gradle plugin with
    // commands that make the Data Hub Framework do its magic
    id 'com.marklogic.ml-data-hub' version '2.0.4'
}

ext {
    mlDeployerDir = "build/ml-data-hub-deployer"
    mlDeployerGroup = "ML DataHub Deployer"
    mlDeployerZipFilename = "ml-data-hub-deployer.zip"
}

/*
 * If the project has the "disconnected" property defined, then we look for
mlcp dependencies in a directory
 * instead of retrieving them from a repository.
 */
if (project.hasProperty("disconnected")) {
    println "\nRUNNING IN DISCONNECTED MODE"

    dependencies {
        compile fileTree(dir: "ml-data-hub-dependencies", include: "*.jar")
    }
}

/*
 * If we're not in disconnected mode, then we grab dependencies from
repositories, and we define a set of tasks
 * for creating the "mlDeployer" zip file that can be used in a
disconnected environment.
 */
else {
    repositories {
        jcenter()
        maven {url 'http://developer.marklogic.com/maven2/'}
    }

    configurations { mlgradle }

    dependencies {
        // this allows you to write custom java code that depends
        // on the Data Hub Framework library
        compile 'com.marklogic:marklogic-data-hub:2.0.4'
        compile 'com.marklogic:marklogic-xcc:9.0.4'
    }

    task copyGradleFiles(type: Copy, group: mlDeployerGroup) {
        from "README.md", "build.gradle", "gradle.properties",
fileTree(dir: ".", include: "gradle-*.properties")
        into mlDeployerDir
    }

    task copyAppModules(type: Copy, group: mlDeployerGroup) {
        from "plugins"
        into mlDeployerDir + "/plugins"
    }

    task copyAppConfig(type: Copy, group: mlDeployerGroup) {
        from "hub-internal-config"
        into mlDeployerDir + "/hub-internal-config"
    }

    task copyEntityConfig(type: Copy, group: mlDeployerGroup) {
        from "entity-config"
        into mlDeployerDir + "/entity-config"
    }

    task copyUserConfig(type: Copy, group: mlDeployerGroup) {
        from "user-config"
        into mlDeployerDir + "/user-config"
    }

    task copyMlDataHubDependencies(type: Copy, group: mlDeployerGroup) {
        from configurations.mlgradle
        into mlDeployerDir + "/ml-data-hub-dependencies"
    }

    task addDisconnectedToGradleProperties {
        doLast {
            ant.propertyfile(file:
"build/ml-data-hub-deployer/gradle.properties") {
                entry(key: "disconnected", value: "true")
            }
        }
    }

    addDisconnectedToGradleProperties.mustRunAfter copyGradleFiles

    task copyMlDeployerFiles(group: mlDeployerGroup) {
        dependsOn = [
            "copyGradleFiles",
            "copyAppModules",
            "copyAppConfig",
            "copyEntityConfig",
            "copyUserConfig",
            "copyMlDataHubDependencies",
            "addDisconnectedToGradleProperties"
        ]
    }

    task deleteMlDeployer(type: Delete, group: mlDeployerGroup) { delete
mlDeployerDir, "build/${mlDeployerZipFilename}" }

    task buildMlDeployer (type: Zip, group: mlDeployerGroup) {
        description "Create a zip of this project's Gradle dependencies and
source code so that it can be deployer without Internet access"
        dependsOn = ["deleteMlDeployer", "copyMlDeployerFiles"]
        from mlDeployerDir
        into 'ml-data-hub-deployer'
        destinationDir file('build')
        archiveName mlDeployerZipFilename
    }

    copyMlDeployerFiles.mustRunAfter deleteMlDeployer
}

/*
 * Below the if/else block, you would have all tasks and other
configuration that is the same, regardless of whether
 * the build is running in disconnected mode or not.
 */

Thanks,
Bhanu Chandra A
