### ISSUE TITLE
gradle hubRunFlow options does not lose dhf prefix

### ISSUE THREAD

**Issue by kghmanuel** [marklogic/marklogic-data-hub#1536]
Based on documentation (https://marklogic.github.io/marklogic-data-hub/docs/gradle-tasks/) the proper way to pass options for gradle task hubRunFlow is to do the following:

```
  -Pdhf.myKey=myValue \
  -Pdhf.myOtherKey=myOtherValue
```

to end up with an options containing the keys `myKey` and `myOtherKey` accordingly. But after adding debug lines, the config received in both collector.xqy and main.xqy contain `dhf.myKey` and `dhf.myOtherKey` respectively.

#### Tech details

Which Operating System are you using? **Windows 7**
Which version of MarkLogic are you using? **9.0-7**
Which version of the Data Hub Framework are you using? **4.0.2**
Is this a QuickStart UI bug? If so, which browser are you using? **N/A**

**Comment by grechaw** [comment]
Looking into this -- it could be that this was never implemented and it's a docs bug.

**Comment by grechaw** [comment]
@kghmanuel have you examined what happens if you simply strip the 'dhf.' from the options?  It doesn't look like the code was written to support it.

**Comment by mhuang-ml** [comment]
@aebadirad, I think we can close this issue?  The latest documentation shows the parameter usage properly (https://marklogic.github.io/marklogic-data-hub/refs/gradle-tasks/) and I would guess that the functionality was tested with the latest build as well?

**Comment by kgmanuel** [comment]
Apologies for the late reply. The referenced docs still says `-Pdhf.myKey=myValue` and it still does not work on my end. I am now using 4.1.0. my command is

```
gradle hubRunFlow -PentityName=WebDocument -PflowName=harmonizeDocsFromDMC -Pdhf.processAll=true
```

**Comment by srinathgit** [comment]
Thanks @kghmanuel . I have created https://project.marklogic.com/jira/browse/DHFPROD-1919 to track this issue

**Comment by aebadirad** [comment]
Fixed in 4.2.2

**Comment by samitintuit** [comment]
I was facing the same issue. After upgrade the DHF to 4.2.2, it still NOT working.
here is my command:
./gradlew ..... -Pdhf.collection=TestUser

but when I printed the value of the above collection parameter in the collect function (collector.sjs), it printed as undefined.
I am printing it as: options.collection in the collect function

**Comment by joecrean** [comment]
@aebadirad 
hey alex, just wanted to say that it was maybe ill advised to roll this change out without checking with existing customers. 
We are using properties with `dhf` since 2.x and after the upgrade from 4.2.0 to 4.3.2 we were hit by this.. ie. the properties suddenly stopped working because of the missing `dhf` ... pity.
